### ISSUE TITLE
前言中不允许有内容

### ISSUE THREAD

**Issue by Synaric** [MarnonDev/GameNews#1]
gradle中报错：前言中不允许有内容
部分日志：

> [Fatal Error] jiecaovideoplayer-4.5_preview1.pom:2:1: 前言中不允许有内容。                                                              
[Fatal Error] jiecaovideoplayer-4.5_preview1.pom:2:1: 前言中不允许有内容。                                                    
[Fatal Error] recyclerview-animators-2.2.3.pom:2:1: 前言中不允许有内容。                                                                
[Fatal Error] recyclerview-animators-2.2.3.pom:2:1: 前言中不允许有内容。                                                                
[Fatal Error] butterknife-8.0.1.pom:2:1: 前言中不允许有内容。                                                                           
[Fatal Error] butterknife-8.0.1.pom:2:1: 前言中不允许有内容。                                                                           
[Fatal Error] gson-2.6.2.pom:2:1: 前言中不允许有内容。                                                                                  
[Fatal Error] gson-2.6.2.pom:2:1: 前言中不允许有内容。                                                                                  
[Fatal Error] rxjava-1.1.6.pom:2:1: 前言中不允许有内容。

**Comment by MarnonDev** [comment]
可能是字符编码的问题，看下你的AS是什么编码格式的，以UTF-8无BOM方式编码即可。

**Comment by Synaric** [comment]
thx 我的工作空间确实是UTF-8的。我看到报错的是POM文件，所以尝试替换掉maven仓库，仍未解决问题。可能是我的AS版本低了吧
